UnsignedBigInteger done
Saloed/softdev-2022-spring-task-1 pull request #1
Opened 2022-02-08 15:34 UTC by Zar1official

Зарецкий Дмитрий Павлович (гр. 3530901/10004) выполнено задание UnsignedBigInteger, пробовал загружать в котоед, но почему-то мне сабмишен закрыли и теперь не отправить туда.

2022-02-08 17:57 UTC, Saloed requested changes

2022-02-08 17:57 UTC, Saloed commented on task/build.gradle.kts
> +    kotlin("jvm") version "1.6.20-M1"
А почему "-M1"?

2022-02-08 17:57 UTC, Saloed commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +class UnsignedBigInteger(private val number: MutableList<Int> = mutableListOf()) : Comparable<UnsignedBigInteger> {
Хранить по одной десятичной цифре в каждом разряде BigInteger это не лучший способ представления

2022-02-08 17:57 UTC, Saloed commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +            return mutableListOf<Int>().apply {
Выглядит как `s.map { ... }`

2022-02-08 17:57 UTC, Saloed commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +            other == UnsignedBigInteger(0) -> throw ArithmeticException(DIVISION_BY_ZERO)
Чего это 0 вычитать нельзя? И странно, что сообщения об ошибках содержат что-то про деление

2022-02-08 18:21 UTC, Zar1official commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +            other == UnsignedBigInteger(0) -> throw ArithmeticException(DIVISION_BY_ZERO)
поправил

2022-02-08 18:21 UTC, Zar1official commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +            return mutableListOf<Int>().apply {
поправил

2022-02-08 18:22 UTC, Zar1official commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +class UnsignedBigInteger(private val number: MutableList<Int> = mutableListOf()) : Comparable<UnsignedBigInteger> {
какое лучше? по моему самое оптимальное в списке с интами хранить, нет?

2022-02-08 18:22 UTC, Zar1official commented on task/build.gradle.kts
> +    kotlin("jvm") version "1.6.20-M1"
понятия не имею. идея сама предложила версию. И судя по всему она только сегодня вышла) https://blog.jetbrains.com/kotlin/2022/02/kotlin-1-6-20-m1-released/

2022-02-08 18:27 UTC, Zar1official commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +class UnsignedBigInteger(private val number: MutableList<Int> = mutableListOf()) : Comparable<UnsignedBigInteger> {
можно byte?

2022-02-08 18:27 UTC, Zar1official commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +class UnsignedBigInteger(private val number: MutableList<Int> = mutableListOf()) : Comparable<UnsignedBigInteger> {
инт жирновато да

2022-02-08 18:29 UTC, Saloed commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +class UnsignedBigInteger(private val number: MutableList<Int> = mutableListOf()) : Comparable<UnsignedBigInteger> {
Идея в том, что в одном Int  можно хранить не число от 0 до 10, а число от 0 до 2^32

2022-02-08 18:31 UTC, Saloed commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +            other == UnsignedBigInteger(0) -> throw ArithmeticException(DIVISION_BY_ZERO)
А сообщение?

2022-02-08 18:35 UTC, Saloed commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +class UnsignedBigInteger(private val number: MutableList<Int> = mutableListOf()) : Comparable<UnsignedBigInteger> {
При этом операции с таким представлением числа почти не менются. Сейчас у вас по сути используется основание системы счисления 10, а можно использовать основание 2^32.

2022-02-08 18:40 UTC, Saloed commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +class UnsignedBigInteger(private val number: MutableList<Int> = mutableListOf()) : Comparable<UnsignedBigInteger> {
И если переходить к такому представлению, то лучше использовать беззнаковый тип [UInt](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-u-int/)

2022-02-10 21:36 UTC, Zar1official commented on task/build.gradle.kts
> +    kotlin("jvm") version "1.6.20-M1"
поправил

2022-02-10 21:37 UTC, Zar1official commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +class UnsignedBigInteger(private val number: MutableList<Int> = mutableListOf()) : Comparable<UnsignedBigInteger> {
перешел к системе счисления 2^32, но сломалось деление, оно работает очень медленно(как следствие взятие остатка) и умножение(я не понимаю как добавлять в "память" когда мы выходим за границы UInt при умножении, при сложении и вычитании придумал как это обойти)

2022-02-10 21:37 UTC, Zar1official commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +            other == UnsignedBigInteger(0) -> throw ArithmeticException(DIVISION_BY_ZERO)
поправил

2022-02-11 08:26 UTC, Saloed requested changes

2022-02-11 08:26 UTC, Saloed commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +                it.digitToInt().toUInt()
А где 2^32? Тут всё ещё по одной десятичной цифре записывается.

2022-02-11 08:26 UTC, Saloed commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +class UnsignedBigInteger(private val number: MutableList<Int> = mutableListOf()) : Comparable<UnsignedBigInteger> {
Можно для вычислений использовать `ULong`. В него точно поместятся все промежуточные значения.

2022-02-17 10:41 UTC, Zar1official commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +class UnsignedBigInteger(private val number: MutableList<Int> = mutableListOf()) : Comparable<UnsignedBigInteger> {
оптимизировал умножение и конструктор из строки и int. деление пока что сделал через поиск очередной цифры через бин поиск, работает быстро

2022-02-17 11:58 UTC, Saloed requested changes

2022-02-17 11:58 UTC, Saloed commented on task/src/test/java/task1/UnsignedBigIntegerTest.kt
> +package task1
Попробуйте сравниваться в тестах с настоящим BigInteger. Найдёте много интересного. Например:
```kotlin
fun UnsignedBigInteger.toBigInteger() = BigInteger("$this")
@Test
fun test(){
    val value = "16414891648916498218168937819263016316213221321"
    val actual = UnsignedBigInteger(value) * UnsignedBigInteger(value)
    val expected = BigInteger(value) * BigInteger(value)
    assertEquals(actual.toBigInteger(), expected)
}
```

2022-02-17 11:58 UTC, Saloed commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +            return mutableListOf<UInt>().apply {
Основание системы счисления при построении числа сейчас не `BASE`, а что-то странное. Из-за этого все вычисления у вас работают неправильно.

2022-02-17 11:58 UTC, Saloed commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +                        current.deleteCharAt(0)
Старайтесь избегать удалений из начала

2022-02-17 22:28 UTC, Zar1official commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +            return mutableListOf<UInt>().apply {
Я не понимаю где именно у меня ошибка? У меня в списке хранятся цифры числа. где каждый элемент это разряд числа. Разряд в данном случае является число от 0 до 2^32-1, верно?

2022-02-20 17:39 UTC, Saloed commented on task/src/test/java/task1/UnsignedBigIntegerTest.kt
> +package task1
Основание системы счисления влияет только на особенности представления чисел внутри. На вычислительных возможностях это не сказывается ни как. С помощью BigInteger можно представить абсолютно любое целое число. Хоть `10^100000000000000000`. К и с помощью вашей реализации. Единственное отличие в  том, что настойщий BigInteger поддерживает отрицательные числа. В остальном, они должны работать абсолютно одинаково.

2022-02-20 17:40 UTC, Saloed commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +            return mutableListOf<UInt>().apply {
То, что вы написали верно, но то, что у вас в коде работает не так.

2022-02-27 08:18 UTC, Saloed requested changes

2022-02-27 08:18 UTC, Saloed commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +    private val BASE: ULong = DEFAULT_BASE
Это всё таки поле, а их принято именовать с маленькой буквы.

2022-02-27 08:18 UTC, Saloed commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +                val d =
Лучше не делать таких переносов. Их появление намекает на то, что возможно выражение сложное и его часть лучше положить в переменную.

2022-02-27 08:18 UTC, Saloed commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +            val res = buildList {
Решение с добавлением поддержки произвольного основания интересное, но у него есть недостаток. Произвольное основание нужно только в двух случаях: создание из строки и превращение в строку. При этом, его приходится учитывать во всех операциях и оно потенциально запрещает использовать те оптимизации, которые можно применять зная, что используются все разряды числа. 

Построить число из строки можно без поддержки основания используя операцию умножения.

2022-02-27 08:18 UTC, Saloed commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +        var result = UnsignedBigInteger(mutableListOf(0u), 10UL)
Здесь тоже можно обойтись без изменения основания. Можно просто делить на 10.

2022-03-03 17:42 UTC, Zar1official commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +                val d =
это я вроде еще в прошлом коммите исправил.

2022-03-03 17:43 UTC, Zar1official commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +                val d =
по крайней мере в коде у себя не вижу такой длинной записи

2022-03-03 17:43 UTC, Zar1official commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +        var result = UnsignedBigInteger(mutableListOf(0u), 10UL)
согласен, так проще

2022-03-03 17:43 UTC, Zar1official commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +            val res = buildList {
можно поподробнее про построение числа из строки через умножение?

2022-03-03 17:44 UTC, Zar1official commented on task/src/test/java/task1/UnsignedBigIntegerTest.kt
> +    fun test() {
добавил тесты для разных случаев

2022-03-03 17:44 UTC, Zar1official commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +    private val BASE: ULong = DEFAULT_BASE
пофиксил

2022-03-04 19:11 UTC, Saloed requested changes

2022-03-04 19:11 UTC, Saloed commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +                val d =
https://github.com/Zar1official/softdev-2022-spring-task-1/blob/57142dbc50322c56ad759979248db9d96c768756/task/src/main/java/task1/UnsignedBigInteger.kt#L90

![image](https://user-images.githubusercontent.com/8640896/156826607-376c42cd-0aec-4dcd-9c14-5b56045a25f0.png)

2022-03-04 19:11 UTC, Saloed commented on task/src/test/java/task1/UnsignedBigIntegerTest.kt
> +                BigInteger(i.first) *
Пофиксите перенос, пожалуйста. Ну очень глаз режет

2022-03-04 19:13 UTC, Saloed commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +            val res = buildList {
Ну что-то в духе

```kotlin
var result = 0
for (digit in str) {
     result *= 10 // основание системы числа, которое в строке
     result += digit
}
````
только для ваших UnsignedBigInteger

2022-03-04 19:56 UTC, Zar1official commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +                val d =
Да, увидел. Ну я там убрал произвольное основание и соотв-но вернул оптимизации из позапрошлого коммита. Часть выражений в отдельные переменные вынес.

2022-03-04 19:56 UTC, Zar1official commented on task/src/main/java/task1/UnsignedBigInteger.kt
> +            val res = buildList {
сделал

2022-03-04 19:57 UTC, Zar1official commented on task/src/test/java/task1/UnsignedBigIntegerTest.kt
> +                BigInteger(i.first) *
пофиксил

2022-03-05 07:58 UTC, Saloed approved these changes

2022-03-05 07:59 UTC, closed without merging