Коваленко Ян, Префиксное дерево, 3530901/10004
Saloed/softdev-2022-spring-task-1 pull request #10
Opened 2022-03-07 11:46 UTC by Flay98

2022-03-07 15:20 UTC, Saloed requested changes

2022-03-07 15:20 UTC, Saloed commented on task/src/main/java/task1/Trie.java
> +                if (node.isWordEnd && c == lastChar) {
Лучше не сравнивать с последней буквой, а проверить индекс.

2022-03-07 15:20 UTC, Saloed commented on task/src/main/java/task1/Trie.java
> +                if (node.isWordEnd && c == lastChar) {
После удаления нужно ещё выкидывать ненужные узлы

2022-03-07 18:48 UTC, Flay98 commented on task/src/main/java/task1/Trie.java
> +                if (node.isWordEnd && c == lastChar) {
> Лучше не сравнивать с последней буквой, а проверить индекс.

исправил

2022-03-07 18:49 UTC, Flay98 commented on task/src/main/java/task1/Trie.java
> +                if (node.isWordEnd && c == lastChar) {
> После удаления нужно ещё выкидывать ненужные узлы

не получилось

2022-03-08 07:58 UTC, Saloed commented
4?

2022-03-08 09:13 UTC, Flay98 commented
> 4?

согласен

2022-03-08 13:10 UTC, closed without merging