Другов Иван, "Группа студентов", 3530901/10004
Saloed/softdev-2022-spring-task-1 pull request #11
Opened 2022-03-07 17:29 UTC by Zmiha

2022-03-08 08:12 UTC, Saloed requested changes
3?

2022-03-08 08:12 UTC, Saloed commented on task/src/main/java/task1/Group.java
> +    private final ArrayList<String> student;
Лучше указывать наиболее абстрактный тип

2022-03-08 08:12 UTC, Saloed commented on task/src/main/java/task1/Group.java
> +        if (student.contains(delname))
`student` это список, а значит операции `contains`, `remove`, `indexOf` будут перебирать все эелементы списка в поисках нужного.

2022-03-08 08:12 UTC, Saloed commented on task/src/main/java/task1/Group.java
> +    public ArrayList<Integer> test = new ArrayList<>();
А эти поля точно нужны?

2022-03-09 12:11 UTC, Saloed commented
Если вы не согласны с 3 и хотите 4, то нужно  исправить все замечания

2022-03-10 02:57 UTC, Zmiha commented
> Если вы не согласны с 3 и хотите 4, то нужно исправить все замечания

Согласен на 3

2022-03-10 08:24 UTC, closed without merging