class
Saloed/softdev-2022-spring-task-1 pull request #13
Opened 2022-03-07 21:30 UTC by dasaguseva

2022-03-08 08:18 UTC, Saloed requested changes
4?

2022-03-08 08:18 UTC, Saloed commented on task/src/main/java/task1/Student.java
> +    private final HashMap<String, Integer> subjects;
Лучше указывать наиболее абстрактный тип

2022-03-08 08:18 UTC, Saloed commented on task/src/main/java/task1/StudentGroup.java
> +    public StudentGroup(Integer number, HashMap<String, Student> group) {
А зачем параметр `group`?

2022-03-08 08:18 UTC, Saloed commented on task/src/main/java/task1/StudentGroup.java
> +    private final Integer number;
А как используется поле `number`?

2022-03-11 08:17 UTC, dasaguseva commented on task/src/main/java/task1/Student.java
> +    private final HashMap<String, Integer> subjects;
с оценкой согласна

2022-03-11 08:26 UTC, closed without merging