Емельянов В.В., "Бинарное дерево поиска", гр. 3530901/10004
Saloed/softdev-2022-spring-task-1 pull request #2
Opened 2022-02-13 18:49 UTC by Unrike

2022-02-15 19:38 UTC, Saloed requested changes

2022-02-15 19:38 UTC, Saloed commented on task/src/main/java/task1/BST.java
> +        Node cur = search(val);
А зачем делать search повторно?

2022-02-15 19:38 UTC, Saloed commented on task/src/main/java/task1/BST.java
> +            del.value = cur.value;
А узел  cur после того, как вы его значение переложили в del, удалять не нужно?

2022-02-15 19:38 UTC, Saloed commented on task/src/main/java/task1/BST.java
> +    public String showNeighbours(int val) {
Метод определения соседей должен возвращать Node по аналогии с search.

2022-02-15 19:38 UTC, Saloed commented on task/src/main/java/task1/BST.java
> +    public String showNeighbours(int val) {
Кстати, строки в человекочитаемом формате обычно возникают довольно редко и только в методах типа toString. Если у вас появляется желание вернуть такую строку где-то ещё, то лучше так не делать.

2022-02-15 19:38 UTC, Saloed commented on task/src/main/java/task1/BST.java
> +    public String showTree() {
Лучше переопределить стандартный метод toString

2022-02-15 19:41 UTC, Unrike commented on task/src/main/java/task1/BST.java
> +        Node cur = search(val);
Что ж, вы правы, сейчас исправлю.

2022-02-15 19:41 UTC, Unrike commented on task/src/main/java/task1/BST.java
> +            del.value = cur.value;
Тоже справедливо.

2022-02-15 19:52 UTC, Unrike commented on task/src/main/java/task1/BST.java
> +    public String showNeighbours(int val) {
Возвращать цифровые значения Node'ов?

2022-02-16 20:27 UTC, Saloed requested changes

2022-02-16 20:27 UTC, Saloed commented on task/src/main/java/task1/BST.java
> +            cur = null;
Так вы просто присвоили null в переменную, а не удалили узел

2022-02-16 20:29 UTC, Saloed commented on task/src/main/java/task1/BST.java
> +    public String showNeighbours(int val) {
На мой взгляд главное, чтобы поведение этого метода было консистентно с search. 
Если search возвращает Node, то и здесь нужно возвращать Node. Если search возвращает значение, то и здесь лучше возвращать значения.

2022-02-16 20:31 UTC, Saloed commented on task/src/main/java/task1/BST.java
> +    public String showNeighbours(int val) {
Возвращать это всё списком не очень хорошо, т.к. в списке не понятно что есть что. Лучше либо завести какой-то класс, либо сделать несколько методов, а не один.

2022-02-17 08:55 UTC, Saloed requested changes

2022-02-17 08:55 UTC, Saloed commented on task/src/main/java/task1/BST.java
> +    public Node showParent(Node cur) {
В таком виде кажется логичнее сделать эти методы методами класса Node

2022-02-17 09:21 UTC, Saloed requested changes

2022-02-17 09:21 UTC, Saloed commented on task/src/main/java/task1/BST.java
> +            delete(cur.value);
А при таком подходе разве не удалится узел del, который правильный?

2022-02-17 11:14 UTC, Saloed commented on task/src/main/java/task1/BST.java
> +            delete(cur.value);
Вообще, подход с рекурсивным вызовом delete выглядит костыльным, т.к. обходит всё дерево. В данном случае искать узел для удаления не нужно, т.к. он у вас уже есть.

2022-02-20 17:44 UTC, Saloed requested changes

2022-02-20 17:44 UTC, Saloed commented on task/src/main/java/task1/BST.java
> +    public void delete(Node cur) {
Осталось добавить метод, который позволит сразу удалять значение, чтобы снаружи не приходилось делать search перед удалением.

2022-02-20 17:53 UTC, Saloed approved these changes

2022-02-20 17:54 UTC, closed without merging