Ким Д. А., "Адресная книга", гр. 3530901/10004
Saloed/softdev-2022-spring-task-1 pull request #3
Opened 2022-02-17 16:12 UTC by KimDamir

2022-02-20 18:07 UTC, Saloed requested changes

2022-02-20 18:07 UTC, Saloed commented on task/src/main/java/taskAddressBook/AddressBook.java
> +    public AddressBook(LinkedHashMap<String, Address> ads) {
Лучше всегда указывать наиболее абстрактный тип. Это позволит сделать код более гибким. Конкретный тип будет появляться только при создании объекта.

2022-02-20 18:07 UTC, Saloed commented on task/src/main/java/taskAddressBook/AddressBook.java
> +    public AddressBook(LinkedHashMap<String, Address> ads) {
Хотелось бы ещё видеть конструктор без параметров. Зачастую хочется создать пустую книгу, а потом заполнять её соответствующими методами.

2022-02-20 18:07 UTC, Saloed commented on task/src/main/java/taskAddressBook/AddressBook.java
> +    public List<String> findResidents(String street) {
Постарайтесь изменить способ хранения данных так, чтобы эта операция не требовала перебора всех записей.

2022-02-20 18:07 UTC, Saloed commented on task/src/main/java/taskAddressBook/AddressBook.java
> +    public List<String> findResidents(String street, int house) {
Аналогично методу выше

2022-02-20 18:07 UTC, Saloed commented on task/src/main/java/taskAddressBook/AddressBook.java
> +        List<String> Residents = new ArrayList<>();
Переменные принято называть с маленькой буквы.

2022-02-24 12:56 UTC, Saloed requested changes

2022-02-24 12:56 UTC, Saloed commented on task/src/main/java/taskAddressBook/AddressBook.java
> +        residentsByStreet.get(street).remove(name);
Удаление из списка будет перебирать все элементы, до тех пор пока не найдёт совпадение и удалит его. Лучше заменить список не что-то другое.

2022-02-24 12:56 UTC, Saloed commented on task/src/main/java/taskAddressBook/AddressBook.java
> +        this.addresses.put(name, ad);
Не вижу добавления в `residentsByStreet`

2022-02-24 12:56 UTC, Saloed commented on task/src/main/java/taskAddressBook/AddressBook.java
> +    public List<String> findResidents(String street, int house) {
Тут всё ещё перебор.

2022-02-24 12:56 UTC, Saloed commented on task/src/test/java/taskAddressBook/AddressBookTest.java
> +        LinkedHashMap<String, Address> addresses = new LinkedHashMap<>();
Слева лучше указать более абстрактный тип

2022-02-25 08:30 UTC, Saloed requested changes

2022-02-25 08:30 UTC, Saloed commented on task/src/main/java/taskAddressBook/AddressBook.java
>          if (!addresses.isEmpty()) {
Это всё можно заменить на вызов метода add

2022-02-25 08:30 UTC, Saloed commented on task/src/main/java/taskAddressBook/AddressBook.java
>      public void changeAddress(String name, Address ad) {
`remove` + `add`?

2022-02-25 08:30 UTC, Saloed commented on task/src/main/java/taskAddressBook/AddressBook.java
>          if (residentsByStreet.containsKey(street)) {
`if` тут вроде не нужен

2022-02-25 12:42 UTC, KimDamir commented on task/src/main/java/taskAddressBook/AddressBook.java
>          if (!addresses.isEmpty()) {
Имеется в виду все что под if? Или  что-то другое? Я не совсем понимаю.

2022-02-25 12:52 UTC, Saloed commented on task/src/main/java/taskAddressBook/AddressBook.java
>          if (!addresses.isEmpty()) {
Да, всё что под if

2022-02-25 12:58 UTC, KimDamir commented on task/src/main/java/taskAddressBook/AddressBook.java
>          if (!addresses.isEmpty()) {
Но у меня add же можно использовать только на set. Но для этого нужно сначала вложить в map new set, а для этого мне нужны проверки на то был ли уже такой адрес в прошлом или нет. Иначе у меня каждый раз set будет обнуляться.

2022-02-25 13:15 UTC, Saloed commented on task/src/main/java/taskAddressBook/AddressBook.java
>          if (!addresses.isEmpty()) {
Я пока не понял о какой проблеме вы говорите

2022-02-26 12:15 UTC, KimDamir commented on task/src/main/java/taskAddressBook/AddressBook.java
>          if (!addresses.isEmpty()) {
Я не понимаю как воспользоваться add. Если я напишу residentsByStreet.get(street).get(house).add(name) сразу, то у меня же будет NullReferenceException?

2022-02-27 07:56 UTC, Saloed commented on task/src/main/java/taskAddressBook/AddressBook.java
>          if (!addresses.isEmpty()) {
Ну вы сначала можете положить в `residentsByStreet ` новую `Map`, а потом можете вызвать `add`. Не совсем понятно, откуда там должен взяться `NPE`.

Ps. Он не `NullReferenceException`, а `NullPointerException`

2022-02-27 14:40 UTC, KimDamir commented on task/src/main/java/taskAddressBook/AddressBook.java
>          if (!addresses.isEmpty()) {
Но если я каждый раз буду класть новый map, то разве у меня не удалятся предыдущие записи?

2022-02-28 13:42 UTC, Saloed requested changes

2022-02-28 13:42 UTC, Saloed commented on task/src/main/java/taskAddressBook/AddressBook.java
> +        for (Map.Entry<Integer, Set<String>> entry : residentsByStreet.get(street).entrySet()) {
Здесь всё таки `if` нужен. 

Ps. Зачастую хочется не наращивать вложенность кода и для этого обычно пишут вот так:
```java

if (...) return residents
for (...) {}

```

2022-02-28 19:48 UTC, Saloed approved these changes

2022-02-28 19:49 UTC, closed without merging