Мурзин С.А., "Адресная книга", гр. 3530901/10004
Saloed/softdev-2022-spring-task-1 pull request #4
Opened 2022-02-17 21:47 UTC by SmurZik

2022-02-20 18:18 UTC, Saloed requested changes

2022-02-20 18:18 UTC, Saloed commented on task/src/main/java/task1/AddressBook.java
> +    public AddressBook(HashMap<String, String> book) {
Лучше всегда указывать наиболее абстрактный тип. Это позволит сделать код более гибким. Конкретный тип будет появляться только при создании объекта.

2022-02-20 18:18 UTC, Saloed commented on task/src/main/java/task1/AddressBook.java
> +    public AddressBook(HashMap<String, String> book) {
Хотелось бы ещё видеть конструктор без параметров. Зачастую хочется создать пустую книгу, а потом заполнять её соответствующими методами.

2022-02-20 18:18 UTC, Saloed commented on task/src/main/java/task1/AddressBook.java
> +    public Map addPair(Map<String, String> book) {
Нужен метод, который позволит добавить одного человека и его адрес. Для такого метода принимать Map не обязательно. В случае, если вы хотите метод, который позволит добавлять много записей сразу, то лучше сделать, чтобы он принимал `AddressBook`. Это позволит иметь более абстрактный код и не привязываться к тому, что `AddressBook` на самом деле это `Map`.

2022-02-20 18:18 UTC, Saloed commented on task/src/main/java/task1/AddressBook.java
> +    public Map deleteAddress(String surname) {
А зачем что-то возвращать?

2022-02-20 18:18 UTC, Saloed commented on task/src/main/java/task1/AddressBook.java
> +    public Set getInhabitantByStreet(String street) {
Постарайтесь изменить способ хранения данных так, чтобы эта операция не требовала перебора всех записей.

2022-02-20 18:18 UTC, Saloed commented on task/src/main/java/task1/AddressBook.java
> +    public Set getInhabitantByHouse (String house) {
Аналогично методу выше

2022-02-20 18:18 UTC, Saloed commented on task/src/main/java/task1/AddressBook.java
> +    public String getStreet(String address) {
Если вы представляете адрес в виде одной строки, то нужно во всех местах, где строка попадает в `AddressBook ` проверять её формат. Иной вариант использовать какое-то другое представление адреса и принимать везде его.

2022-02-28 09:29 UTC, Saloed requested changes

2022-02-28 09:29 UTC, Saloed commented on task/src/main/java/task1/AddressBook.java
> +    public void setMap(Map adr) {
Лучше не использовать типы без  указания их generic параметров

2022-02-28 09:29 UTC, Saloed commented on task/src/main/java/task1/AddressBook.java
> +    public void setInhabitants(String sur, Address adr) {
Этот метод публичный и его можно вызвать снаружи. При этом, вызов этого метода может привести объект в некорректное состояние, т.к. он не добавляет запись в `adresses`.

2022-02-28 19:58 UTC, Saloed requested changes

2022-02-28 19:58 UTC, Saloed commented on task/src/main/java/task1/AddressBook.java
>          addresses = adr;
Обратите внимание, что если `Map`, который передан как `adr` будет где-то изменён, то и поле `adresses` поменяется, а значит объект может прийти в некорректное состояние. Такого быть не должно

2022-02-28 19:58 UTC, Saloed commented on task/src/main/java/task1/AddressBook.java
> +        String street = addresses.get(surname).street;
Хотелось бы, чтобы в случае, если такого `surname` нет, всё не падало с `NPE`.

2022-02-28 19:58 UTC, Saloed commented on task/src/test/java/task1/AddressBookTest.java
> +        HashMap<String, Address> b1 = new HashMap<>();
Тип?

2022-02-28 20:55 UTC, SmurZik commented on task/src/main/java/task1/AddressBook.java
>          addresses = adr;
Не совсем понимаю, как это можно исправить

2022-03-05 14:26 UTC, Saloed requested changes

2022-03-05 14:26 UTC, Saloed commented on task/src/main/java/task1/AddressBook.java
> +        if (addresses.containsKey(surname)) {
Можно уменьшить вложенность кода, если сделать 
```java
if (!condition) return
```

2022-03-05 14:26 UTC, Saloed commented on task/src/main/java/task1/AddressBook.java
> +        String oldString = addresses.get(surname).street;
Здесь может быть `NPE`

2022-03-05 14:26 UTC, Saloed commented on task/src/main/java/task1/AddressBook.java
>          addresses = adr;
Вам необходимо сделать так, чтобы у поля `addresses` ссылка не совпадала с  `adr`.

2022-03-07 15:01 UTC, Saloed requested changes

2022-03-08 08:04 UTC, closed without merging