Шкроба Дарья, задача 11 "прейскурант" 3530901/10004
Saloed/softdev-2022-spring-task-1 pull request #5
Opened 2022-02-19 12:07 UTC by shkrobadasha

2022-02-20 18:30 UTC, Saloed requested changes

2022-02-20 18:30 UTC, Saloed commented on task/src/main/java/task1/PriceList.java
> +    PriceList(String strproducts,String strprices){
Лучше не делать конструкторов, которые занимаются каким-то парсингом. Если вы хотите уметь создавать объект из списка товаров, то и принимать лучше список. А  если хочется парсинг, то можно вынести его в статический метод.

2022-02-20 18:30 UTC, Saloed commented on task/src/main/java/task1/PriceList.java
> +        if (products.contains(name)) {
contains в списке это нехорошо. Он перебирает все элементы в списке. Аналогично с indexOf.

2022-02-20 18:30 UTC, Saloed commented on task/src/main/java/task1/PriceList.java
> +    public void add(String name, Double price) {
Т.к. ваша штука выдаёт id товарам, то было бы хорошо возвращать их при добавлении товара. Ну или добавить метод, который позволит узнать id товара. Иначе не понтяно, как пользоваться методами, которые принимают id, если мы его не можем узнать.

2022-02-20 18:30 UTC, Saloed commented on task/src/main/java/task1/PriceList.java
> +        if (id < 0 || id > prices.size()-1) return;
Просто return в таком случае это нехорошо. Лучше либо вернуть какой-то статус, либо кинуть исключение в случае отсутствия id.

2022-02-20 18:30 UTC, Saloed commented on task/src/main/java/task1/PriceList.java
> +        if (!products.contains(name)) return;
Аналогично `add`

2022-03-07 15:09 UTC, Saloed requested changes

2022-03-07 15:09 UTC, Saloed commented on task/src/main/java/task1/PriceList.java
> +    private final HashMap<Integer, InfOfProducts> listOfPrices;
Лучше указывать наиболее абстрактный тип

2022-03-07 15:09 UTC, Saloed commented on task/src/main/java/task1/PriceList.java
> +    public void addElement(String name, double price) {
Если товар с таким названием у нас уже был, то наверное надо как-то это обработать. Но можно на это забить и считать, что имена у нас могут повторяться, а чтобы отличать товары как раз и нужен `id`.

2022-03-07 15:09 UTC, Saloed commented on task/src/main/java/task1/PriceList.java
> +    public void replaceCost(int id, Double newcost) {
А почему `Double`, а не `double`?

2022-03-07 15:09 UTC, Saloed commented on task/src/main/java/task1/PriceList.java
> +        for (Integer key : listOfPrices.keySet())
Можно хранить какую-то дополнительную информацию и избавиться от перебора

2022-03-07 15:12 UTC, Saloed commented
Нужно определиться с уникальность названий товаров:
1. Названия уникальны. Тогда при добавлении это нужно проверять.
2. Названия не уникальны. Тогда при создании нужно возвращать `id`, а функция `getId` не имеет смысла, т.к. по имени однозначно определить `id` товара нельзя.

2022-03-08 08:05 UTC, Saloed commented
4?

2022-03-08 10:17 UTC, shkrobadasha commented
> 4?

Да,дайте оставим 4.

2022-03-08 13:09 UTC, closed without merging