Алмаметов Эмиль, "Библиотека", 3530901/10004
Saloed/softdev-2022-spring-task-1 pull request #7
Opened 2022-02-25 11:46 UTC by leunamme4

2022-02-25 13:20 UTC, Saloed requested changes

2022-02-25 13:20 UTC, Saloed commented on task/src/main/java/task1/BookLibrary.java
> +    ArrayList<Book> Books;
Лучше всегда указывать наиболее абстрактный тип. Это позволит сделать код более гибким. Конкретный тип будет появляться только при создании объекта.

2022-02-25 13:20 UTC, Saloed commented on task/src/main/java/task1/BookLibrary.java
> +    ArrayList<Book> Books;
Переменные и поля в `Java` принято называть с маленькой буквы

2022-02-25 13:20 UTC, Saloed commented on task/src/main/java/task1/BookLibrary.java
> +        private final String list;
А зачем нужно это поле?

2022-02-25 13:20 UTC, Saloed commented on task/src/main/java/task1/BookLibrary.java
> +        for (int i = 0; i < Books.size(); i++) {
Постарайтесь хранить данные так, чтобы для данной операции не нужно было перебирать все книги

2022-02-25 13:20 UTC, Saloed commented on task/src/main/java/task1/BookLibrary.java
> +        for (Book book : Books) {
Постарайтесь хранить данные так, чтобы для данной операции не нужно было перебирать все книги

2022-02-25 13:20 UTC, Saloed commented on task/src/main/java/task1/BookLibrary.java
> +        for (Book book : Books) {
Постарайтесь хранить данные так, чтобы для данной операции не нужно было перебирать все книги

2022-02-25 13:20 UTC, Saloed commented on task/src/main/java/task1/BookLibrary.java
> +        for (Book book : Books) {
Постарайтесь хранить данные так, чтобы для данной операции не нужно было перебирать все книги

2022-02-25 13:20 UTC, Saloed commented on task/src/main/java/task1/BookLibrary.java
> +        for (Book book : Books) {
Постарайтесь хранить данные так, чтобы для данной операции не нужно было перебирать все книги

2022-02-25 13:20 UTC, Saloed commented on task/src/main/java/task1/BookLibrary.java
> +    public String search(String bookName, String bookAuthor, String bookGenre, String bookShelf) {
Лучше возвращать книгу, а не строку

2022-02-28 17:17 UTC, leunamme4 commented on task/src/main/java/task1/BookLibrary.java
> +    public String search(String bookName, String bookAuthor, String bookGenre, String bookShelf) {
Сделал коммит, где исправил замечания.

2022-02-28 20:05 UTC, Saloed approved these changes

2022-02-28 20:05 UTC, closed without merging