Маянцев В.С., "Адресная книга", гр. 3530901/10004
Saloed/softdev-2022-spring-task-1 pull request #8
Opened 2022-03-02 20:20 UTC by Mayanzev

2022-03-05 15:13 UTC, Saloed requested changes

2022-03-05 15:13 UTC, Saloed commented on task/src/main/java/task1/AddressBook.java
> +    public AddressBook(Map<String, Address> addresses) {
Хотелось бы иметь конструктор без параметров

2022-03-05 15:13 UTC, Saloed commented on task/src/main/java/task1/AddressBook.java
> +        for (Map.Entry<String, Address> pair: bookAddresses.entrySet()) {
Попробуйте хранить какое-то дополнительное представление данных об адресах, чтобы для данной операции не требовался перебор

2022-03-05 15:13 UTC, Saloed commented on task/src/main/java/task1/AddressBook.java
> +        for (Map.Entry<String, Address> pair: bookAddresses.entrySet()) {
Попробуйте хранить какое-то дополнительное представление данных об адресах, чтобы для данной операции не требовался перебор

2022-03-07 11:24 UTC, Saloed commented on task/src/main/java/task1/AddressBook.java
> +        this.bookAddresses = addresses;
Обратите внимание, что если Map, который передан как addressesбудет где-то изменён, то и поле bookAddresses поменяется, а значит объект может прийти в некорректное состояние. Такого быть не должно.

2022-03-08 08:05 UTC, Saloed commented
4?

2022-03-08 08:12 UTC, Mayanzev commented
Да, 4 было бы прекрасно

2022-03-08 13:09 UTC, closed without merging